export interface Dados {
    Nome_muda: any,
    Nome_cultivo: any,
    Imagem_muda: any,
    Imagem_cultivo: any,
    Imagem_estagios_1: any,
    Imagem_estagios_2: any,
    Imagem_estagios_3: any,
    Imagem_estagios_4: any,
    Imagem_estagios_5: any,
    Imagem_colheita_1: any,
    Imagem_colheita_2: any,
    desc_cultivo_1: any,
    desc_cultivo_2: any,
    Estacao: any,
    Energia: any,
    Preco_de_venda_cultivo: any,
    Estagio_1_descricao: any,
    Estagio_2_descricao: any,
    Estagio_3_descricao: any,
    Estagio_4_descricao: any,
    Estagio_5_descricao: any,
    Colheita_1_descricao: any,
    Colheita_2_descricao: any,
}
